language: python
python:
#  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# command to install dependencies
install:
  - pip install ply

# command to run tests
script:
  - python -m mybuild.test.test_solver
  - python -m mylang.test.test_parser
  - python -m test.module_tests_solver
